### ISSUE TITLE
Icon-SDK-Java: Static code check - minor issues found (Bugs and Vulnerabilities)

### ISSUE THREAD

**Issue by Tjure07** [icon-project/icon-sdk-java#7]
Hello,

a static scan of the Icon-SDK-Java showed a few issues (bugs and vulnerabilities):

https://sonarcloud.io/dashboard?id=ICX-Java-SDK

Please take a look into the scan results and consider the mentioned recommendations.

Thanks.

**Comment by whylee259** [comment]
The major issues have been fixed in the last version (0.9.10)

> https://github.com/icon-project/icon-sdk-java/blob/master/CHANGELOG.md#version-0910---december-21-2018-maven

Thank you
